export const SET_HOMEPRICE = 'SET_HOMEPRICE';
export const SET_INCOME = 'SET_INCOME';
export const SET_INTEREST_RATE = 'SET_INTEREST_RATE';
export const SET_PROPERTY_TAX_RATE = 'SET_PROPERTY_TAX_RATE';
export const SET_PROPERTY_INSURANCE_RATE = 'SET_PROPERTY_INSURANCE_RATE';
